services:
  - type: web
    name: movierama-api
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: API_READ_ACCESS_TOKEN
        sync: false
      - key: API_KEY
        sync: false
